# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
 use_frameworks!

inhibit_all_warnings!

target 'RetailKitProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
   pod 'Moya', '~> 13.0.0-beta.1'
   pod 'SnapKit', '~> 4.2.0'
   pod 'IQKeyboardManagerSwift'
   pod 'MJRefresh', '~> 3.1.15.7'
   pod 'SwiftyRSA'
   pod 'Masonry'
   pod 'HandyJSON'
   pod 'Kingfisher'
#   pod 'MBProgressHUD', '~> 1.1.0'
#   pod 'YYImage', '~> 1.0.4'

#pod 'AMap3DMap' #3D地图SDK #
pod 'AMap2DMap', '~> 5.6.0'#2D地图SDK (2D和3D不能同时使用) 5.6.0
pod 'AMapSearch' #搜索功能
pod 'AMapLocation' #定位SDK
pod 'JPush'#极光推送
pod 'SwiftyJSON', '~> 4.0'

#pod 'SDWebImage', '~> 4.3.3'


end
